import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/General/(Color Manager)/ThemeController";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-color-mode="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {children}
        </ThemeProvider>

        {/* 🔔 Global Toast Notifications */}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: "#0f0f0f",
              color: "#ffffff",
              border: "1px solid rgba(255,255,255,0.08)",
              fontFamily: "monospace",
            },
            success: {
              iconTheme: {
                primary: "#22c55e",
                secondary: "#0f0f0f",
              },
            },
            error: {
              iconTheme: {
                primary: "#ef4444",
                secondary: "#0f0f0f",
              },
            },
          }}
        />
      </body>
    </html>
  );
}